### ISSUE TITLE
FR: support oauth restricted login

### ISSUE THREAD

**Issue by doubledgedboard** [cosmocode/dokuwiki-plugin-usermanagerextended#1]
When using the [oauth](https://www.dokuwiki.org/plugin:oauth) plugin, with self-register disabled, and the plugin's 'singleService' option enabled (which allows users to register themselves with oauth even when self-regsiter is disabled), the registration process fails due to the usermanagerextended plugin.

I would love to be able to still have users self-register with oauth, and also still give managers the ability to manage users.

I'm not sure where the problem lies, so this is just a basic feature request. If I get a bunch of free time to look into it, I will happily open a PR, otherwise if anyone else is interested, please consider it :)

**Comment by splitbrain** [comment]
@annda maybe it would make sense to apply the restrictions only when the events are triggered within the user manager?

**Comment by annda** [comment]
Please check the latest release, I included a check suggested by @splitbrain

**Comment by doubledgedboard** [comment]
@annda it works! Thanks!

Closed by https://github.com/cosmocode/dokuwiki-plugin-usermanagerextended/commit/a1694fc3000459172f1c32262f0364e0a20ff239
